---
# tasks/main.yml

- name: Test need for subscription setup if katello cert exists
  ansible.builtin.stat:
    path: /etc/pki/ca-trust/source/anchors/katello-server-ca.pem
  register: r_katello_cert_stat

- name: Only run subscription setup if katello cert does not exist
  when: not r_katello_cert_stat.stat.exists
  block:

  - name: Install CA certificate from satellite server
    ansible.builtin.get_url:
      url: "https://{{ set_repositories_satellite_hostname }}/pub/katello-server-ca.crt"
      dest: /etc/pki/ca-trust/source/anchors/{{ set_repositories_satellite_hostname }}.ca.crt
      mode: u=rw,go=r
      validate_certs: false
    retries: 10
    delay: 10

  - name: Update CA Trust Bundle
    command: update-ca-trust

  - name: Install Satellite CA certificate package
    ansible.builtin.dnf:
      name: "https://{{ set_repositories_satellite_hostname }}/pub/katello-ca-consumer-latest.noarch.rpm"
      state: present
      disablerepo: "*"
      disable_gpg_check: true
    register: r_install_satellite_ca_rpm
    until: not r_install_satellite_ca_rpm.failed
    retries: 10
    delay: 10

  - name: Disable Reporting Of Package Profile to Satellite
    community.general.ini_file:
      path: /etc/rhsm/rhsm.conf
      section: rhsm
      option: report_package_profile
      value: "0"

  - name: Register with activation-key with HA
    when: set_repositories_satellite_ha is defined and set_repositories_satellite_ha|bool == True
    community.general.redhat_subscription:
      state: present
      consumer_name: "{{ set_repositories_subscription_hostname }}"
      server_hostname: "{{ set_repositories_satellite_hostname }}"
      server_port: "8443"
      server_prefix: /rhsm
      rhsm_baseurl: "https://{{ set_repositories_satellite_hostname }}/pulp/repos"
      activationkey: "{{ set_repositories_satellite_activationkey }}"
      org_id: "{{ set_repositories_satellite_org | default(satellite_org) }}"
      force_register: "{{ set_repositories_force_register | default('false') }}"

  - name: Enable RHSM to manage repositories
    command: subscription-manager config --rhsm.manage_repos=1
